stages:
  - build

before_script:
  - add-apt-repository ppa:longsleep/golang-backports
  - apt update
  - apt install golang-go

build:
  stage: build
  script:
    - go build
  artifacts:
    paths:
      - filereplace