stages:
  - build

before_script:
  - sudo add-apt-repository ppa:longsleep/golang-backports
  - sudo apt update
  - sudo apt install golang-go

build:
  stage: build
  script:
    - go build
  artifacts:
    paths:
      - filereplace