stages:
  - build

before_script:
  - wget https://golang.org/dl/go1.17.linux-amd64.tar.gz
  - tar -xzf -C /usr/local ./go1.17.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin


build:
  stage: build
  script:
    - go build
  artifacts:
    paths:
      - filereplace